### PR TITLE
Issues/195

### PR DESCRIPTION
**Pull request by alexsok-bit**
* Reident indentations to 4 spaces instead Tabs
* Replaced all a string literals as a comment to a normal comment lines
* Reformat all code for PEP8
* Remove all unused imports
* added .gitignore file
* added .editorconfig file for presets editors [WTF](https://editorconfig.org/)

### CODE REVIEW

**Comment by Greenwolf** [comment]
Hey mate, this looks great, looks like your on a bit of a coding spree, I don't suppose you have any thoughts into how to fix the facebook rate limiting? I've used their /async path to grab larger profile pictures from the search page, but they are limiting it now. So i'm thinking maybe we need to navigate to the profile page, click grab the profile picture link to make larger, then grab the static image from this?

Interested to hear your thoughts if you think there is a more efficient way to do this?

**Comment by alexsok-bit** [comment]
For now I will just refactor a code of project. So about the Facebook I just remove an unused import. Or `import facebook` is needed?

**Comment by alexsok-bit** [comment]
And may be I can fix a problem with the facebook rate limit)

**Comment by Greenwolf** [comment]
Yeah, if you want to have a look at it and have any ideas, it would be awesome to get a 2nd opinion!

**Comment by Greenwolf** [comment]
Thanks you again for the updates, i'm merging

**Pull request merged**
